=== tlau10/Methodenbank/Methoden/Kategorie A/Eisenstadt 1.4/03 Source Code/Eisenstadt-Code/xmlFiles/xsd/busSimulation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Bussimulation"><!-- Rootelement, Bussimulation -->
    <xs:complexType>
      <xs:sequence><!-- Child Elements, were written out -->
        <xs:element ref="Strassennetz"/>
        <xs:element ref="SimuKonfiguration"/>
        <xs:element ref="SimuPanel"/>
        <xs:element ref="VirtualGrid"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Strassennetz"><!-- Strassennetz -->
    <xs:complexType>
      <xs:sequence><!-- Child Elements -->
        <xs:element ref="Haltestellen" minOccurs="0" maxOccurs="unbounded"/><!-- optional Childs -->
        <xs:element ref="Planquadrate" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="Ziele" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="Linien" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="GesperrteFelder" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Planquadrate"><!-- Planquadrate -->
    <xs:complexType>
      <xs:sequence><!-- optional sequences -->
        <xs:element ref="PlanquadratStrasse" minOccurs="0" maxOccurs="unbounded"/><!-- Strassen -->
        <xs:element ref="PlanquadratGesperrteStrasse" minOccurs="0" maxOccurs="unbounded"/><!-- Gesperrte Strassen -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PlanquadratStrasse"><!-- Strassen -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Strasse" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/><!-- Id -->
    </xs:complexType>
  </xs:element>
  <xs:element name="Strasse"><!-- Element Strasse -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GesamtKosten"/><!-- Childs -->
        <xs:element ref="KostenStartBisPunkt"/>
        <xs:element ref="KostenPunktBisZiel"/>
        <xs:element ref="Point"/>
        <xs:element ref="Feldgroesse"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/><!-- Id -->
      <xs:attribute name="art" use="required"/><!-- Kind of Planquadrat -->
    </xs:complexType>
  </xs:element>
  <xs:element name="PlanquadratGesperrteStrasse"><!-- Gesperrte Strassen -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GesperrteStrasse" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/><!-- Id -->
    </xs:complexType>
  </xs:element>
  <xs:element name="GesperrteStrasse">
    <xs:complexType>
      <xs:sequence><!-- Childs -->
        <xs:element ref="GesamtKosten"/>
        <xs:element ref="KostenStartBisPunkt"/>
        <xs:element ref="KostenPunktBisZiel"/>
        <xs:element ref="Point"/>
        <xs:element ref="Feldgroesse"/>
      </xs:sequence>
      <xs:attribute name="art" use="required"/><!-- Kind of the barred Way -->
      <xs:attribute name="id" use="required"/><!-- Id -->
    </xs:complexType>
  </xs:element>
  <xs:element name="Ziele"><!-- Ziele -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ziel" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Ziel"><!-- goal -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/><!--  name of the goal -->
        <xs:element ref="Point"/><!-- point of the goal, where is set up -->
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Linien"><!-- Linien -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Linie" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Linie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Haltestellen"/>
        <xs:element ref="Teilstrecken"/>
        <xs:element ref="Color"/>
        <xs:element ref="MaxKapazitaetPassagiere"/>
        <xs:element ref="Wiederkehrzeit"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Color" /><!-- simple Element -->
  <xs:element name="MaxKapazitaetPassagiere" /><!-- simple Element -->
  <xs:element name="Wiederkehrzeit" /><!-- simple Element -->
  <xs:element name="GesperrteFelder">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GesperrtesFeld" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GesperrtesFeld"><!-- Gesperrte Haltestelle -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Point"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimuKonfiguration"><!-- Simulation Configuration -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="AktuelleAufloesung"/>
        <xs:element ref="GroessePlanquadrat"/>
        <xs:element ref="EinstellungenFrame"/>
        <xs:element ref="GroesseFeldelement"/>
        <xs:element ref="BusGeschwindigkeit"/>
        <xs:element ref="GehGeschwindigkeit"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AktuelleAufloesung">
    <xs:complexType>
      <xs:attribute name="resHeight" use="required"/>
      <xs:attribute name="resWidth" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="GroessePlanquadrat"/>
  <xs:element name="EinstellungenFrame">
    <xs:complexType>
      <xs:attribute name="height" use="required"/>
      <xs:attribute name="width" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="GroesseFeldelement"/><!-- simple Element -->
  <xs:element name="BusGeschwindigkeit"/><!-- simple Element -->
  <xs:element name="GehGeschwindigkeit" /><!-- simple Element -->
  <xs:element name="SimuPanel"><!-- SimuPanel, important for the simulation part -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GroesseEditor"/>
        <xs:element ref="GroesseFelder"/>
        <xs:element ref="AnzahlFelder"/>
        <xs:element ref="BackgroundImage"/>
        <xs:element ref="Haltestellen"/>
        <xs:element ref="BusPanels"/>
        <xs:element ref="BenoetigteBusse"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GroesseEditor"/><!-- simple Element -->
  <xs:element name="GroesseFelder"/><!-- simple Element -->
  <xs:element name="AnzahlFelder"/><!-- simple Element -->
  <xs:element name="BackgroundImage">
    <xs:complexType>
      <xs:attribute name="height" use="required"/>
      <xs:attribute name="url" use="required"/>
      <xs:attribute name="width" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BusPanels">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="BusPanel" minOccurs="0" maxOccurs="unbounded"/><!-- BusPanel -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="BusPanel">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Image"/>
        <xs:element ref="Bus"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Image">
    <xs:complexType>
      <xs:attribute name="height" use="required"/>
      <xs:attribute name="url" use="required"/>
      <xs:attribute name="width" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BenoetigteBusse">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Bus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VirtualGrid" /><!-- VirtualGrid, simple Type -->
  <xs:element name="Haltestellen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Haltestelle" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Haltestelle">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" minOccurs="0" />
        <xs:element ref="Kapazitaet" minOccurs="0" />
        <xs:element ref="Point" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Kapazitaet"/><!-- simple Element -->
  <xs:element name="GesamtKosten"/><!-- simple Element -->
  <xs:element name="KostenStartBisPunkt"/><!-- simple Element -->
  <xs:element name="KostenPunktBisZiel"/><!-- simple Element -->
  <xs:element name="Point"><!-- Point, with Coordinates -->
    <xs:complexType>
      <xs:attribute name="xEnd"/>
      <xs:attribute name="xStart"/>
      <xs:attribute name="xValue"/>
      <xs:attribute name="yEnd"/>
      <xs:attribute name="yStart"/>
      <xs:attribute name="yValue"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Feldgroesse">
    <xs:complexType>
      <xs:attribute name="height" use="required"/>
      <xs:attribute name="width" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name"/>
  <xs:element name="Teilstrecken"><!-- Teilstrecken -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Teilstrecke" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Teilstrecke">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="StartPoint"/>
        <xs:element ref="EndPoint"/>
        <xs:element ref="Geschwindigkeit"/>
        <xs:element ref="Breite"/>
        <xs:element ref="Laenge"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StartPoint"><!-- Start of a Point -->
    <xs:complexType>
      <xs:attribute name="xValue" use="required"/>
      <xs:attribute name="yValue" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EndPoint"><!-- End of a Point -->
    <xs:complexType>
      <xs:attribute name="xValue" use="required"/>
      <xs:attribute name="yValue" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Geschwindigkeit"/><!-- simple Element -->
  <xs:element name="Breite"/><!-- simple Element -->
  <xs:element name="Laenge"/><!-- simple Element -->
  <xs:element name="Bus">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element ref="BusLinie"/>
        <xs:element ref="HaltestelleJ"/>
        <xs:element ref="PassagierQueue"/>
        <xs:element ref="MaxKapazitaet"/>
        <xs:element ref="Position"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BusLinie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="HaltestellenJ"/>
        <xs:element ref="MaxKapazitaet"/>
        <xs:element ref="Teilstrecken"/>
      </xs:sequence>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HaltestellenJ">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="HaltestelleJ" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PassagierQueue"><!-- Warteschlange, Passagiere -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="DurchschnittsLaenge"/>
        <xs:element ref="DurchschnittsWarteZeit"/>
        <xs:element ref="PassagierQueueLimit"/>
        <xs:element ref="PassagierQueueStrategie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PassagierQueueLimit"/>
  <xs:element name="PassagierQueueStrategie"/>
  <xs:element name="Position">
    <xs:complexType>
      <xs:attribute name="xValue" use="required"/>
      <xs:attribute name="yValue" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HaltestelleJ">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="BusWarteschlangeQueue" minOccurs="0"/>
        <xs:element ref="PassagierWarteschlangeQueue" minOccurs="0"/>
        <xs:element ref="Point" minOccurs="0"/>
        <xs:element ref="BusEinheiten" minOccurs="0"/>
        <xs:element ref="MaxKapazitaet" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="BusWarteschlangeQueue">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="DurchschnittsLaenge"/>
        <xs:element ref="DurchschnittsWarteZeit"/>
        <xs:element ref="WarteschlangenLimit"/>
        <xs:element ref="WarteschlangenStrategie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PassagierWarteschlangeQueue">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="DurchschnittsLaenge"/>
        <xs:element ref="DurchschnittsWarteZeit"/>
        <xs:element ref="WarteschlangenLimit"/>
        <xs:element ref="WarteschlangenStrategie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="BusEinheiten"/>
  <xs:element name="MaxKapazitaet"/>
  <xs:element name="DurchschnittsLaenge"/>
  <xs:element name="DurchschnittsWarteZeit"/>
  <xs:element name="WarteschlangenLimit"/>
  <xs:element name="WarteschlangenStrategie"/>
</xs:schema>

=== tlau10/Methodenbank/Methodenbank/Methoden/Kategorie A/Eisenstadt 1.4/04 Archiv/Eisenstadt 1.3/01 Programm/xmlFiles/xml/document.xml
<?xml version="1.0"?>
<Bussimulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/busSimulation.xsd">
	<Strassennetz>
	
		<!--  set an Haltestellen -->
		<Haltestellen>
			<!-- Haltestellen Werte -->
			<Haltestelle id="">
				<Name></Name>
				<Kapazitaet></Kapazitaet>
				<Point xValue="" yValue=""/>
			</Haltestelle>
		</Haltestellen>
		
		<!--  set an Planquadraten -->
		<Planquadrate>
		    <PlanquadratStrasse id=""><!--  to count the Streets  -->
				<Strasse id="" art="">
		        	<GesamtKosten></GesamtKosten>
		            <KostenStartBisPunkt></KostenStartBisPunkt>
		            <KostenPunktBisZiel></KostenPunktBisZiel>
		            <Point xStart="" yStart="" xEnd="" yEnd=""/>
		            <Feldgroesse width="" height=""/>
		        </Strasse>
			</PlanquadratStrasse>
			<PlanquadratGesperrteStrasse id=""><!--  to count the barredWays  -->
				<GesperrteStrasse id="" art="">
		        	<GesamtKosten></GesamtKosten>
		            <KostenStartBisPunkt></KostenStartBisPunkt>
		            <KostenPunktBisZiel></KostenPunktBisZiel>
		            <Point xStart="" yStart="" xEnd="" yEnd=""/>
		            <Feldgroesse width="" height=""/>
		        </GesperrteStrasse>
			</PlanquadratGesperrteStrasse>
		</Planquadrate>
		
		<!--  set an Zielen -->
		<Ziele>
			<Ziel id=""><!--  ein Ziel -->
				<Name></Name>
				<Point xValue="" yValue=""/>
			</Ziel>
		</Ziele>
		
		<!--  set an Linien -->
		<Linien>
			<Linie id="">
				<Haltestellen><!--  set an Haltestellen -->
					<Haltestelle id=""/>
				</Haltestellen>
				<Teilstrecken><!--  set an Teilstrecken -->
					<Teilstrecke id="">
						<Name></Name>
						<StartPoint xValue="" yValue=""/>
						<EndPoint xValue="" yValue=""/>
						<Geschwindigkeit></Geschwindigkeit>
						<Breite></Breite>
						<Laenge></Laenge>
					</Teilstrecke>
				</Teilstrecken>
				<Color></Color>
				<MaxKapazitaetPassagiere></MaxKapazitaetPassagiere>
				<Wiederkehrzeit></Wiederkehrzeit>
			</Linie>
		</Linien>
		
		<!--  set an gesperrte Felder -->
		<GesperrteFelder>
			<GesperrtesFeld id="">
				<Name></Name>
				<Point xValue="" yValue=""/>
			</GesperrtesFeld>
		</GesperrteFelder>

	</Strassennetz>
	
	<!--  SimuKonfiguration  -->
	<SimuKonfiguration>
		<AktuelleAufloesung resWidth="" resHeight=""/>
		<GroessePlanquadrat></GroessePlanquadrat>
		<EinstellungenFrame width="" height=""/>
		<GroesseFeldelement></GroesseFeldelement>
		<BusGeschwindigkeit></BusGeschwindigkeit>
		<GehGeschwindigkeit></GehGeschwindigkeit>
	</SimuKonfiguration>
	
	<!--  SimuPanel  -->
	<SimuPanel>
		<GroesseEditor></GroesseEditor>
		<GroesseFelder></GroesseFelder>
		<AnzahlFelder></AnzahlFelder>
		<BackgroundImage url="" width="" height=""/>
		<Haltestellen>
			<Haltestelle id=""/>
		</Haltestellen>
		<BusPanels>
			<BusPanel>
				<Image url="" width="" height=""/>
				<Bus id=""><!--  Bus Object -->
					<BusLinie id="">
						<HaltestellenJ>
							<HaltestelleJ>
								<BusWarteschlangeQueue>
									<Name></Name>
									<DurchschnittsLaenge></DurchschnittsLaenge>
									<DurchschnittsWarteZeit></DurchschnittsWarteZeit>
									<WarteschlangenLimit></WarteschlangenLimit>
									<WarteschlangenStrategie></WarteschlangenStrategie>
								</BusWarteschlangeQueue>
								<PassagierWarteschlangeQueue>
									<Name></Name>
									<DurchschnittsLaenge></DurchschnittsLaenge>
									<DurchschnittsWarteZeit></DurchschnittsWarteZeit>
									<WarteschlangenLimit></WarteschlangenLimit>
									<WarteschlangenStrategie></WarteschlangenStrategie>
								</PassagierWarteschlangeQueue>
								<Point xValue="" yValue=""/>
								<BusEinheiten></BusEinheiten>
								<MaxKapazitaet></MaxKapazitaet>
							</HaltestelleJ>
						</HaltestellenJ>
						<MaxKapazitaet></MaxKapazitaet>
						<Teilstrecken><!--  set an Teilstrecken -->
							<Teilstrecke id="">
								<Name></Name>
								<StartPoint xValue="" yValue=""/>
								<EndPoint xValue="" yValue=""/>
								<Geschwindigkeit></Geschwindigkeit>
								<Breite></Breite>
								<Laenge></Laenge>
							</Teilstrecke>
						</Teilstrecken>
					</BusLinie>
					<HaltestelleJ>
						<BusWarteschlangeQueue>
							<Name></Name>
							<DurchschnittsLaenge></DurchschnittsLaenge>
							<DurchschnittsWarteZeit></DurchschnittsWarteZeit>
							<WarteschlangenLimit></WarteschlangenLimit>
							<WarteschlangenStrategie></WarteschlangenStrategie>
						</BusWarteschlangeQueue>
						<PassagierWarteschlangeQueue>
							<Name></Name>
							<DurchschnittsLaenge></DurchschnittsLaenge>
							<DurchschnittsWarteZeit></DurchschnittsWarteZeit>
							<WarteschlangenLimit></WarteschlangenLimit>
							<WarteschlangenStrategie></WarteschlangenStrategie>
						</PassagierWarteschlangeQueue>
						<Point xValue="" yValue=""/>
						<BusEinheiten></BusEinheiten>
						<MaxKapazitaet></MaxKapazitaet>
					</HaltestelleJ>
					<PassagierQueue>
						<Name></Name>
						<DurchschnittsLaenge></DurchschnittsLaenge>
						<DurchschnittsWarteZeit></DurchschnittsWarteZeit>
						<PassagierQueueLimit></PassagierQueueLimit>
						<PassagierQueueStrategie></PassagierQueueStrategie>
					</PassagierQueue>
					<MaxKapazitaet></MaxKapazitaet>
					<Position xValue="" yValue=""/>
				</Bus>
			</BusPanel>
		</BusPanels>
		<BenoetigteBusse>
			<Bus id=""/>
		</BenoetigteBusse>
	</SimuPanel>
	
	<!--  VirtualGrid  -->
	<VirtualGrid>
		<!--  gets Data from SimuKonfiguration -->
	</VirtualGrid>
	
</Bussimulation>

=== tlau10/Methodenbank/Methoden/Kategorie A/Eisenstadt 1.4/04 Archiv/Eisenstadt 1.3/01 Programm/xmlFiles/xml/Test.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<Bussimulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\OR-Methoden\Eisenstadt\xmlFiles\xsd\busSimulation.xsd">
  <Strassennetz>
    <Haltestellen>
      <Haltestelle id="1">
        <Name>Haltestelle 2</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="448" yValue="279" />
      </Haltestelle>
      <Haltestelle id="2">
        <Name>Haltestelle 6</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="409" yValue="318" />
      </Haltestelle>
      <Haltestelle id="3">
        <Name>Haltestelle 4</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="123" yValue="344" />
      </Haltestelle>
      <Haltestelle id="4">
        <Name>Haltestelle 5</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="305" yValue="292" />
      </Haltestelle>
      <Haltestelle id="5">
        <Name>Haltestelle 7</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="383" yValue="487" />
      </Haltestelle>
      <Haltestelle id="6">
        <Name>Haltestelle 1</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="396" yValue="422" />
      </Haltestelle>
      <Haltestelle id="7">
        <Name>Haltestelle 3</Name>
        <Kapazitaet>1</Kapazitaet>
        <Point xValue="253" yValue="292" />
      </Haltestelle>
    </Haltestellen>
    <Planquadrate>
      <PlanquadratStrasse id="11">
        <Strasse id="11" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="169" yStart="325" xEnd="286" yEnd="299" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="12">
        <Strasse id="12" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="130" yStart="351" xEnd="169" yEnd="325" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="13">
        <Strasse id="13" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="416" yStart="325" xEnd="429" yEnd="299" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="0">
        <Strasse id="0" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="455" yStart="507" xEnd="468" yEnd="546" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="1">
        <Strasse id="1" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="286" yStart="299" xEnd="325" yEnd="312" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="2">
        <Strasse id="2" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="39" yStart="416" xEnd="130" yEnd="351" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="3">
        <Strasse id="3" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="416" yStart="442" xEnd="455" yEnd="507" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="4">
        <Strasse id="4" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="494" yStart="273" xEnd="546" yEnd="273" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="5">
        <Strasse id="5" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="468" yStart="546" xEnd="481" yEnd="598" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="6">
        <Strasse id="6" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="416" yStart="364" xEnd="416" yEnd="325" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="7">
        <Strasse id="7" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="325" yStart="312" xEnd="416" yEnd="442" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="8">
        <Strasse id="8" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="377" yStart="585" xEnd="416" yEnd="364" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="9">
        <Strasse id="9" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="429" yStart="299" xEnd="494" yEnd="273" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
      <PlanquadratStrasse id="10">
        <Strasse id="10" art="isStreet">
          <GesamtKosten>0</GesamtKosten>
          <KostenStartBisPunkt>0</KostenStartBisPunkt>
          <KostenPunktBisZiel>0</KostenPunktBisZiel>
          <Point xStart="546" yStart="273" xEnd="611" yEnd="286" />
          <Feldgroesse width="13.0" height="13.0" />
        </Strasse>
      </PlanquadratStrasse>
    </Planquadrate>
    <Ziele>
      <Ziel id="0">
        <Name>Ziel [9, 29]</Name>
        <Point xValue="123" yValue="383" />
      </Ziel>
      <Ziel id="1">
        <Name>Ziel [18, 21]</Name>
        <Point xValue="240" yValue="279" />
      </Ziel>
      <Ziel id="2">
        <Name>Ziel [25, 27]</Name>
        <Point xValue="331" yValue="357" />
      </Ziel>
      <Ziel id="3">
        <Name>Ziel [29, 32]</Name>
        <Point xValue="383" yValue="422" />
      </Ziel>
      <Ziel id="4">
        <Name>Ziel [33, 21]</Name>
        <Point xValue="435" yValue="279" />
      </Ziel>
      <Ziel id="5">
        <Name>Ziel [43, 19]</Name>
        <Point xValue="565" yValue="253" />
      </Ziel>
      <Ziel id="6">
        <Name>Ziel [31, 39]</Name>
        <Point xValue="409" yValue="513" />
      </Ziel>
      <Ziel id="7">
        <Name>Ziel [38, 28]</Name>
        <Point xValue="500" yValue="370" />
      </Ziel>
      <Ziel id="8">
        <Name>Ziel [46, 28]</Name>
        <Point xValue="604" yValue="370" />
      </Ziel>
      <Ziel id="9">
        <Name>Ziel [40, 33]</Name>
        <Point xValue="526" yValue="435" />
      </Ziel>
    </Ziele>
  </Strassennetz>
  <SimuKonfiguration>
    <AktuelleAufloesung resWidth="1024" resHeight="768" />
    <GroessePlanquadrat>13</GroessePlanquadrat>
    <EinstellungenFrame width="330" height="400" />
    <GroesseFeldelement>65.0</GroesseFeldelement>
    <BusGeschwindigkeit>40.0</BusGeschwindigkeit>
    <GehGeschwindigkeit>6.0</GehGeschwindigkeit>
  </SimuKonfiguration>
  <SimuPanel>
    <GroesseEditor>640</GroesseEditor>
    <GroesseFelder>13</GroesseFelder>
    <AnzahlFelder>49</AnzahlFelder>
    <BackgroundImage url="/D:/OR-Methoden/Eisenstadt/bin/Eisenstadt.jpg" width="840" height="840" />
    <Haltestellen>
      <Haltestelle id="5" />
      <Haltestelle id="3" />
      <Haltestelle id="2" />
      <Haltestelle id="7" />
      <Haltestelle id="1" />
      <Haltestelle id="4" />
      <Haltestelle id="6" />
    </Haltestellen>
    <BusPanels />
    <BenoetigteBusse />
  </SimuPanel>
  <VirtualGrid>-- gets Data from SimuKonfiguration --</VirtualGrid>
</Bussimulation>
